修改代码提交逻辑

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -2,3 +2,10 @@
 . "$(dirname -- "$0")/_/husky.sh"
 
 npm run format
+
+if [ $? -ne 0 ]; then
+  echo "Prettier formatting failed."
+  exit 1
+fi
+
+exit 0
